module rv32i_top (
`ifdef USE_POWER_PINS
    inout vccd1,
    inout vssd1,
    inout vccd2,
    inout vssd2,
    inout vdda1,
    inout vssa1,
    inout vdda2,
    inout vssa2,
`endif
    input  clk,
    input  rst,

    // Wishbone Interface
    input         wb_clk_i,
    input         wb_rst_i,
    input         wbs_stb_i,
    input         wbs_cyc_i,
    input         wbs_we_i,
        input \wbs_sel_i[0] ,
    input \wbs_sel_i[1] ,
    input \wbs_sel_i[2] ,
    input \wbs_sel_i[3] ,
        input \wbs_dat_i[0] ,
    input \wbs_dat_i[1] ,
    input \wbs_dat_i[2] ,
    input \wbs_dat_i[3] ,
    input \wbs_dat_i[4] ,
    input \wbs_dat_i[5] ,
    input \wbs_dat_i[6] ,
    input \wbs_dat_i[7] ,
    input \wbs_dat_i[8] ,
    input \wbs_dat_i[9] ,
    input \wbs_dat_i[10] ,
    input \wbs_dat_i[11] ,
    input \wbs_dat_i[12] ,
    input \wbs_dat_i[13] ,
    input \wbs_dat_i[14] ,
    input \wbs_dat_i[15] ,
    input \wbs_dat_i[16] ,
    input \wbs_dat_i[17] ,
    input \wbs_dat_i[18] ,
    input \wbs_dat_i[19] ,
    input \wbs_dat_i[20] ,
    input \wbs_dat_i[21] ,
    input \wbs_dat_i[22] ,
    input \wbs_dat_i[23] ,
    input \wbs_dat_i[24] ,
    input \wbs_dat_i[25] ,
    input \wbs_dat_i[26] ,
    input \wbs_dat_i[27] ,
    input \wbs_dat_i[28] ,
    input \wbs_dat_i[29] ,
    input \wbs_dat_i[30] ,
    input \wbs_dat_i[31] ,
        input \wbs_adr_i[0] ,
    input \wbs_adr_i[1] ,
    input \wbs_adr_i[2] ,
    input \wbs_adr_i[3] ,
    input \wbs_adr_i[4] ,
    input \wbs_adr_i[5] ,
    input \wbs_adr_i[6] ,
    input \wbs_adr_i[7] ,
    input \wbs_adr_i[8] ,
    input \wbs_adr_i[9] ,
    input \wbs_adr_i[10] ,
    input \wbs_adr_i[11] ,
    input \wbs_adr_i[12] ,
    input \wbs_adr_i[13] ,
    input \wbs_adr_i[14] ,
    input \wbs_adr_i[15] ,
    input \wbs_adr_i[16] ,
    input \wbs_adr_i[17] ,
    input \wbs_adr_i[18] ,
    input \wbs_adr_i[19] ,
    input \wbs_adr_i[20] ,
    input \wbs_adr_i[21] ,
    input \wbs_adr_i[22] ,
    input \wbs_adr_i[23] ,
    input \wbs_adr_i[24] ,
    input \wbs_adr_i[25] ,
    input \wbs_adr_i[26] ,
    input \wbs_adr_i[27] ,
    input \wbs_adr_i[28] ,
    input \wbs_adr_i[29] ,
    input \wbs_adr_i[30] ,
    input \wbs_adr_i[31] ,
    output        wbs_ack_o,
        output \wbs_dat_o[0] ,
    output \wbs_dat_o[1] ,
    output \wbs_dat_o[2] ,
    output \wbs_dat_o[3] ,
    output \wbs_dat_o[4] ,
    output \wbs_dat_o[5] ,
    output \wbs_dat_o[6] ,
    output \wbs_dat_o[7] ,
    output \wbs_dat_o[8] ,
    output \wbs_dat_o[9] ,
    output \wbs_dat_o[10] ,
    output \wbs_dat_o[11] ,
    output \wbs_dat_o[12] ,
    output \wbs_dat_o[13] ,
    output \wbs_dat_o[14] ,
    output \wbs_dat_o[15] ,
    output \wbs_dat_o[16] ,
    output \wbs_dat_o[17] ,
    output \wbs_dat_o[18] ,
    output \wbs_dat_o[19] ,
    output \wbs_dat_o[20] ,
    output \wbs_dat_o[21] ,
    output \wbs_dat_o[22] ,
    output \wbs_dat_o[23] ,
    output \wbs_dat_o[24] ,
    output \wbs_dat_o[25] ,
    output \wbs_dat_o[26] ,
    output \wbs_dat_o[27] ,
    output \wbs_dat_o[28] ,
    output \wbs_dat_o[29] ,
    output \wbs_dat_o[30] ,
    output \wbs_dat_o[31] ,

    // JTAG
    input  jtag_tck,
    input  jtag_tms,
    input  jtag_tdi,
    output jtag_tdo,
    input  jtag_trst_n,

    // BIST
    input  bist_mode_ext,
    output bist_done_ext,
    output bist_pass_ext,

    // IRQ
        output \irq[0] ,
    output \irq[1] ,
    output \irq[2] ,

    // Caravel wrapper tie-offs
        output \io_out[0] ,
    output \io_out[1] ,
    output \io_out[2] ,
    output \io_out[3] ,
    output \io_out[4] ,
    output \io_out[5] ,
    output \io_out[6] ,
    output \io_out[7] ,
    output \io_out[8] ,
    output \io_out[9] ,
    output \io_out[10] ,
    output \io_out[11] ,
    output \io_out[12] ,
    output \io_out[13] ,
    output \io_out[14] ,
    output \io_out[15] ,
    output \io_out[16] ,
    output \io_out[17] ,
    output \io_out[18] ,
    output \io_out[19] ,
    output \io_out[20] ,
    output \io_out[21] ,
    output \io_out[22] ,
    output \io_out[23] ,
    output \io_out[24] ,
    output \io_out[25] ,
    output \io_out[26] ,
    output \io_out[27] ,
    output \io_out[28] ,
    output \io_out[29] ,
    output \io_out[30] ,
    output \io_out[31] ,
    output \io_out[32] ,
    output \io_out[33] ,
    output \io_out[34] ,
    output \io_out[35] ,
    output \io_out[36] ,
    output \io_out[37] ,
        output \io_oeb[0] ,
    output \io_oeb[1] ,
    output \io_oeb[2] ,
    output \io_oeb[3] ,
    output \io_oeb[4] ,
    output \io_oeb[5] ,
    output \io_oeb[6] ,
    output \io_oeb[7] ,
    output \io_oeb[8] ,
    output \io_oeb[9] ,
    output \io_oeb[10] ,
    output \io_oeb[11] ,
    output \io_oeb[12] ,
    output \io_oeb[13] ,
    output \io_oeb[14] ,
    output \io_oeb[15] ,
    output \io_oeb[16] ,
    output \io_oeb[17] ,
    output \io_oeb[18] ,
    output \io_oeb[19] ,
    output \io_oeb[20] ,
    output \io_oeb[21] ,
    output \io_oeb[22] ,
    output \io_oeb[23] ,
    output \io_oeb[24] ,
    output \io_oeb[25] ,
    output \io_oeb[26] ,
    output \io_oeb[27] ,
    output \io_oeb[28] ,
    output \io_oeb[29] ,
    output \io_oeb[30] ,
    output \io_oeb[31] ,
    output \io_oeb[32] ,
    output \io_oeb[33] ,
    output \io_oeb[34] ,
    output \io_oeb[35] ,
    output \io_oeb[36] ,
    output \io_oeb[37] ,
        output \la_data_out[0] ,
    output \la_data_out[1] ,
    output \la_data_out[2] ,
    output \la_data_out[3] ,
    output \la_data_out[4] ,
    output \la_data_out[5] ,
    output \la_data_out[6] ,
    output \la_data_out[7] ,
    output \la_data_out[8] ,
    output \la_data_out[9] ,
    output \la_data_out[10] ,
    output \la_data_out[11] ,
    output \la_data_out[12] ,
    output \la_data_out[13] ,
    output \la_data_out[14] ,
    output \la_data_out[15] ,
    output \la_data_out[16] ,
    output \la_data_out[17] ,
    output \la_data_out[18] ,
    output \la_data_out[19] ,
    output \la_data_out[20] ,
    output \la_data_out[21] ,
    output \la_data_out[22] ,
    output \la_data_out[23] ,
    output \la_data_out[24] ,
    output \la_data_out[25] ,
    output \la_data_out[26] ,
    output \la_data_out[27] ,
    output \la_data_out[28] ,
    output \la_data_out[29] ,
    output \la_data_out[30] ,
    output \la_data_out[31] ,
    output \la_data_out[32] ,
    output \la_data_out[33] ,
    output \la_data_out[34] ,
    output \la_data_out[35] ,
    output \la_data_out[36] ,
    output \la_data_out[37] ,
    output \la_data_out[38] ,
    output \la_data_out[39] ,
    output \la_data_out[40] ,
    output \la_data_out[41] ,
    output \la_data_out[42] ,
    output \la_data_out[43] ,
    output \la_data_out[44] ,
    output \la_data_out[45] ,
    output \la_data_out[46] ,
    output \la_data_out[47] ,
    output \la_data_out[48] ,
    output \la_data_out[49] ,
    output \la_data_out[50] ,
    output \la_data_out[51] ,
    output \la_data_out[52] ,
    output \la_data_out[53] ,
    output \la_data_out[54] ,
    output \la_data_out[55] ,
    output \la_data_out[56] ,
    output \la_data_out[57] ,
    output \la_data_out[58] ,
    output \la_data_out[59] ,
    output \la_data_out[60] ,
    output \la_data_out[61] ,
    output \la_data_out[62] ,
    output \la_data_out[63] ,
    output \la_data_out[64] ,
    output \la_data_out[65] ,
    output \la_data_out[66] ,
    output \la_data_out[67] ,
    output \la_data_out[68] ,
    output \la_data_out[69] ,
    output \la_data_out[70] ,
    output \la_data_out[71] ,
    output \la_data_out[72] ,
    output \la_data_out[73] ,
    output \la_data_out[74] ,
    output \la_data_out[75] ,
    output \la_data_out[76] ,
    output \la_data_out[77] ,
    output \la_data_out[78] ,
    output \la_data_out[79] ,
    output \la_data_out[80] ,
    output \la_data_out[81] ,
    output \la_data_out[82] ,
    output \la_data_out[83] ,
    output \la_data_out[84] ,
    output \la_data_out[85] ,
    output \la_data_out[86] ,
    output \la_data_out[87] ,
    output \la_data_out[88] ,
    output \la_data_out[89] ,
    output \la_data_out[90] ,
    output \la_data_out[91] ,
    output \la_data_out[92] ,
    output \la_data_out[93] ,
    output \la_data_out[94] ,
    output \la_data_out[95] ,
    output \la_data_out[96] ,
    output \la_data_out[97] ,
    output \la_data_out[98] ,
    output \la_data_out[99] ,
    output \la_data_out[100] ,
    output \la_data_out[101] ,
    output \la_data_out[102] ,
    output \la_data_out[103] ,
    output \la_data_out[104] ,
    output \la_data_out[105] ,
    output \la_data_out[106] ,
    output \la_data_out[107] ,
    output \la_data_out[108] ,
    output \la_data_out[109] ,
    output \la_data_out[110] ,
    output \la_data_out[111] ,
    output \la_data_out[112] ,
    output \la_data_out[113] ,
    output \la_data_out[114] ,
    output \la_data_out[115] ,
    output \la_data_out[116] ,
    output \la_data_out[117] ,
    output \la_data_out[118] ,
    output \la_data_out[119] ,
    output \la_data_out[120] ,
    output \la_data_out[121] ,
    output \la_data_out[122] ,
    output \la_data_out[123] ,
    output \la_data_out[124] ,
    output \la_data_out[125] ,
    output \la_data_out[126] ,
    output \la_data_out[127]
);
endmodule
